name: Trigger CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST -u "${{ secrets.TRIGGER_PAT_USERNAME_JS }}:${{ secrets.TRIGGER_PAT_TOKEN_JS }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/Trusted-AI-Labs/APTITUDE_Toolbox_docker/actions/workflows/CI.yml/dispatches \
              -d '{"ref": "main"}'
